In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('/content/credit_card_default.csv')

In [6]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_1                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

No encoding required
Checking missing values

In [61]:
df.isnull().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_1                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
nextpayment                   0
dtype: int64

In [10]:
#There is no missing values

In [11]:
#Removing ID Column
df.drop('ID',axis = 1,inplace=True)

In [12]:
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   30000 non-null  int64
 1   SEX                         30000 non-null  int64
 2   EDUCATION                   30000 non-null  int64
 3   MARRIAGE                    30000 non-null  int64
 4   AGE                         30000 non-null  int64
 5   PAY_1                       30000 non-null  int64
 6   PAY_2                       30000 non-null  int64
 7   PAY_3                       30000 non-null  int64
 8   PAY_4                       30000 non-null  int64
 9   PAY_5                       30000 non-null  int64
 10  PAY_6                       30000 non-null  int64
 11  BILL_AMT1                   30000 non-null  int64
 12  BILL_AMT2                   30000 non-null  int64
 13  BILL_AMT3                   30000 non-null  int64
 14  BILL_AMT4                   30000 non-null  int64
 15  BILL_AMT5                   30000 non-null  int64
 16  BILL_AMT6                   30000 non-null  int64
 17  PAY_AMT1                    30000 non-null  int64
 18  PAY_AMT2                    30000 non-null  int64
 19  PAY_AMT3                    30000 non-null  int64
 20  PAY_AMT4                    30000 non-null  int64
 21  PAY_AMT5                    30000 non-null  int64
 22  PAY_AMT6                    30000 non-null  int64
 23  default payment next month  30000 non-null  int64
dtypes: int64(24)
memory usage: 5.5 MB

In [14]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [15]:
#changing 'default payment next month' column name into 'nextpayment' beacause of an error

In [16]:
df['nextpayment'] = df['default payment next month']

In [17]:
x = df.drop(columns=['nextpayment'],axis=1)
y = df.nextpayment

In [18]:
x

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000,1,3,1,39,0,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,150000,1,3,2,43,-1,-1,-1,-1,0,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,30000,1,2,2,37,4,3,2,-1,0,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,80000,1,3,1,41,1,-1,0,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,50000,1,2,1,46,0,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=42)

In [20]:
#Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [22]:
#importing libraries kNN,SVC,GradientBoosting,AdaBoost,xgb

In [23]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
import xgboost as xgb

In [24]:
knn_classifier = KNeighborsClassifier()
svm_classifier = SVC()
gb_classifier = GradientBoostingClassifier()
ada_classifier = AdaBoostClassifier()
xgb_classifier = xgb.XGBClassifier()

In [25]:
#Training

In [26]:
knn_classifier.fit(x_train_scaled, y_train)
svm_classifier.fit(x_train_scaled, y_train)
gb_classifier.fit(x_train_scaled, y_train)
ada_classifier.fit(x_train_scaled, y_train)
xgb_classifier.fit(x_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [27]:
#Making Predictions

In [28]:
knn_preds = knn_classifier.predict(x_test_scaled)
svm_preds = svm_classifier.predict(x_test_scaled)
gb_preds = gb_classifier.predict(x_test_scaled)
ada_preds = ada_classifier.predict(x_test_scaled)
xgb_preds = xgb_classifier.predict(x_test_scaled)

In [29]:
#Checking Accuracy

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
knn_accuracy = accuracy_score(y_test, knn_preds)
svm_accuracy = accuracy_score(y_test, svm_preds)
gb_accuracy = accuracy_score(y_test, gb_preds)
ada_accuracy = accuracy_score(y_test, ada_preds)
xgb_accuracy = accuracy_score(y_test, xgb_preds)

In [32]:
print("k-NN Accuracy:", knn_accuracy,
      ("SVM Accuracy:", svm_accuracy),
      ("GBA:", gb_accuracy),
      ("AdaBoost Accuracy:", ada_accuracy),
      ("XGB Accuracy:", xgb_accuracy))

k-NN Accuracy: 0.9952 ('SVM Accuracy:', 0.9986666666666667) ('GBA:', 1.0) ('AdaBoost Accuracy:', 1.0) ('XGB Accuracy:', 1.0)

In [33]:
#Tuning

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold

In [35]:
kf = KFold(n_splits = 10)

In [36]:
for train_index, test_index in kf.split(x,y):
  print('Training Index',train_index)
  print('Test Index',test_index)

Training Index [ 3000  3001  3002 ... 29997 29998 29999]
Test Index [   0    1    2 ... 2997 2998 2999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [3000 3001 3002 ... 5997 5998 5999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [6000 6001 6002 ... 8997 8998 8999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [ 9000  9001  9002 ... 11997 11998 11999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [12000 12001 12002 ... 14997 14998 14999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [15000 15001 15002 ... 17997 17998 17999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [18000 18001 18002 ... 20997 20998 20999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [21000 21001 21002 ... 23997 23998 23999]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [24000 24001 24002 ... 26997 26998 26999]
Training Index [    0     1     2 ... 26997 26998 26999]
Test Index [27000 27001 27002 ... 29997 29998 29999]

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [38]:
model = LogisticRegression(max_iter=100)
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
score = cross_val_score(model,x,y,cv = kf)
print("Cross Validation Scores are{}".format(score))

In [40]:
#By default it return the accuracy score

In [41]:
print('Averge Cross Validaton Score is {}'.format(score.mean()))

Averge Cross Validaton Score is 0.7787333333333334

In [42]:
#Stratified K Fold

In [43]:
from sklearn.model_selection import StratifiedKFold

In [44]:
skfold_validator = StratifiedKFold (n_splits = 10)

In [45]:
for train_index, test_index in skfold_validator.split(x,y):
  print('Training Index', train_index)
  print('Test Index', test_index)

Training Index [ 2993  2995  2996 ... 29997 29998 29999]
Test Index [   0    1    2 ... 3001 3004 3005]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [2993 2995 2996 ... 6044 6045 6047]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [5983 5984 5985 ... 9030 9032 9033]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [ 8883  8886  8888 ... 12047 12048 12049]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [11794 11796 11802 ... 15067 15068 15069]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [14766 14770 14778 ... 18217 18218 18220]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [17316 17319 17323 ... 21194 21196 21197]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [20429 20437 20439 ... 24071 24072 24073]
Training Index [    0     1     2 ... 29997 29998 29999]
Test Index [23691 23696 23704 ... 26997 26998 26999]
Training Index [    0     1     2 ... 26997 26998 26999]
Test Index [27000 27001 27002 ... 29997 29998 29999]

In [46]:
skcv_results = cross_val_score(model,x, y, cv = skfold_validator)
skcv_results

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0.77866667, 0.77866667, 0.77866667, 0.77866667, 0.778     ,
       0.77866667, 0.779     , 0.77933333, 0.77966667, 0.779     ])

In [47]:
print('Averge Stratified Cross Validaton Score is {}'.format(skcv_results.mean()))

Averge Stratified Cross Validaton Score is 0.7788333333333333

In [48]:
#Tuning with decision tree

In [49]:
from sklearn import tree

In [50]:
#performs cross-validation with different values

In [51]:
max_depth = [1,2,3,4,5,6,7,8,9,10]

In [52]:
for val in max_depth:
  score = cross_val_score(tree.DecisionTreeClassifier(max_depth = val), x, y, cv = kf, scoring = 'accuracy')
  print(f'Average score{val}): {"{:.3f}".format(score.mean())}')

Average score1): 1.000
Average score2): 1.000
Average score3): 1.000
Average score4): 1.000
Average score5): 1.000
Average score6): 1.000
Average score7): 1.000
Average score8): 1.000
Average score9): 1.000
Average score10): 1.000

In [53]:
# Define a hyperparameter grid
parameters ={'n_estimators': [100, 200],
    'max_depth': [10, 2],
    'criterion': ['gini','entropy']
}

In [54]:
from sklearn.model_selection import GridSearchCV

In [55]:
# Create the grid search object

In [56]:
from sklearn.ensemble import RandomForestClassifier
grid_search = GridSearchCV(
    RandomForestClassifier(),
    parameters,
    cv = 5,# 5-fold cross-validation
    scoring = 'accuracy',# Evaluation metric
    n_jobs = -1
)

In [57]:
#fit the grid search

In [58]:
grid_result = grid_search.fit(x_train,y_train)

In [59]:
# Get the best parameters and best score

In [60]:
print('Best Params: ', grid_result.best_params_)
print('Best Score: ', grid_result.best_score_*100)

Best Params:  {'criterion': 'gini', 'max_depth': 10, 'n_estimators': 100}
Best Score:  100.0